### ISSUE TITLE
Matplotlib 2.0

### ISSUE THREAD

**Issue by blaylockbk** [python-windrose/windrose#57] opened 2017-05-16 15:58 UTC
```python
C:\Users\u0553130\AppData\Local\Continuum\Anaconda2\lib\site-packages\matplotlib\cbook.py:136: MatplotlibDeprecationWarning: **The axisbg attribute was deprecated in version 2.0. Use facecolor instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)**
C:\Users\u0553130\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\lib\function_base.py:804: RuntimeWarning: invalid value encountered in greater_equal
  not_smaller_than_edge = (sample[:, i] >= edges[i][-1])
C:\Users\u0553130\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\fromnumeric.py:2822: RuntimeWarning: invalid value encountered in rint
  return round(decimals, out)
```

**Comment by scls19fr** [comment] 2017-05-16 18:10
It seems that this issue is a duplicate of https://github.com/python-windrose/windrose/issues/49
which was fixed in master branch

https://github.com/python-windrose/windrose#install-latest-development-version

So I'm closing. Please reopen if necessary

**Closed by scls19fr** 2017-05-16 18:10 UTC
