### ISSUE TITLE
wind rose axis

### ISSUE THREAD

**Issue by Umercia** [python-windrose/windrose#151] opened 2020-12-01 10:07 UTC
Hi,

It seems that the default directions along the axis circle is not correct anymore.  0° pointing to East
To use the example in the example notebook:

%matplotlib inline
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import numpy as np
from math import pi
from windrose import WindroseAxes

N = 500
ws = np.random.random(N)*6
wd = np.random.random(N)*360
df = pd.DataFrame({"speed": ws, "direction": wd})

ax = WindroseAxes.from_ax()
ax.bar(df.direction, df.speed, normed=True, opening=0.8, edgecolor='white')
ax.set_legend()
![2020-12-01_11h05_02](https://user-images.githubusercontent.com/17033333/100726436-3d014780-33c5-11eb-9886-517ef443c33b.png)

**Comment by rngadam** [comment] 2020-12-25 19:12
Same here with Windrose 1.6.8:

![Screenshot 2020-12-25 at 2 11 02 PM](https://user-images.githubusercontent.com/538542/103140934-18924580-46bb-11eb-88f4-a58fbc67f10e.png)

**Comment by rngadam** [comment] 2020-12-25 19:17
Duplicate of #147 ?

**Comment by waldowda** [comment] 2020-12-27 21:12
I see the same thing and numbers not directions are labeled. I had to add the axes presumably setting the '0' to E as compensation but the labeling seems off by 90° as noted above.

`ax.set_xticklabels(['E', 'NE','N', 'NW',  'W', 'SW', 'S', 'SE'])`

**Comment by FFT1368** [comment] 2021-02-26 04:40
This is an important issue in which the theta labels in windrose are incorrect. for solving it you can type this line in your code.
Solution:
ax.set_xticklabels((90, 45, 0, 315, 270, 225, 180, 135))

**Comment by FFT1368** [comment] 2021-02-26 04:40
Complete code after solution:

from windrose import WindroseAxes
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import numpy as np
plt.figure()

# Create wind speed and direction variables
ws = np.random.random(500) * 25
wd = np.random.random(500) * 360
ax = WindroseAxes.from_ax()
plt.style.use('fast')
ax.bar(wd, ws, nsector= 36,opening=0.94, bins=np.arange(0, 31, 5),edgecolor='gray',lw=0.1)
ax.set_xticklabels([90, 45, 0, 315, 270, 225, 180, 135])

ax.set_legend()
ax.set_title("Wind Rose")

plt.show()

**Comment by FFT1368** [comment] 2021-02-26 05:58
And for having all the grids and numbers every 10 degrees you can use this improved version:



from windrose import WindroseAxes
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import numpy as np
plt.figure()

ws = np.random.random(500) * 25
wd = np.random.random(500) * 360
ax = WindroseAxes.from_ax()
plt.style.use('fast')
ax.bar(wd, ws, nsector= 36,opening=0.94, bins=np.arange(0, 31, 5),edgecolor='gray',lw=0.1)
ax.set_thetagrids(range(0,360,10),[90, 80, 70, 60, 50, 40, 30, 20, 10, 0, 350, 340, 330, 320, 310, 300, 290, 280, 270, 260, 250, 240, 230, 220, 210, 200, 190, 180, 170, 160, 150, 140, 130, 120, 110, 100])
ax.set_theta_zero_location('W', offset=-90)
ax.set_theta_direction(-1)

ax.set_legend()
ax.set_title("Wind Rose")

plt.show()

**Comment by swartmilan** [comment] 2021-03-31 13:32
@FFT1368 Thank you for your post, I encountered this same issue and fixed it myself, only thinking ofo coming to the known issues section after the fact :/ 

In your solution, are you keeping the 'W' direction at the _theta = 0_ location on the polar plot? What is your reason for doing this? Another solution would be to set the theta_zero_location to 'N' and then make the _offset=0_, with the direction going clockwise of course. 

Code below (incomplete code, showing only additions to the 'usual' windrose plot things):
`matplotlib.projections.polar.PolarAxes.set_theta_zero_location(ax, loc="N", offset=0.0)
 matplotlib.projections.polar.PolarAxes.set_theta_direction(ax, direction=-1)
 matplotlib.projections.polar.PolarAxes.set_thetagrids(ax,
                                                           angles=[0,45,90,135,180,225,270,315],
                                                           labels=["N","NE","E","SE","S","SW","W","NW"],
                                                           fmt='str')`

Example:
![image](https://user-images.githubusercontent.com/45619503/113152024-fa962d00-9235-11eb-9418-e93b951e6f35.png)


Is there a reason you did not go this route that I am missing? I'm thinking there might be issues with the labels only moving with the data remaining plotted in the same locations for instance. Otherwise if it works the same then 'N' in the _theta=0_ location would be preferable right?

**Comment by FFT1368** [comment] 2021-04-01 03:51
@swartmilan
Dear Mr.  swartmilan,
I kept theta=0 on West for our company purpose. But if you need to label North as Theta=0 you can use this code for labeling.
I hope it is useful. Please find the program below:


from windrose import WindroseAxes
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import numpy as np


ws = np.random.random(500) * 25
wd = np.random.random(500) * 360
ax = WindroseAxes.from_ax()
plt.style.use('fast')
ax.bar(wd, ws, nsector= 36,opening=0.94, bins=np.arange(0, 31, 5),edgecolor='gray',lw=0.1)
ax.set_thetagrids(range(0,360,10),[90, 80, 70, 60, 50, 40, 30, 20, 10, 0, 350, 340, 330, 320, 310, 300, 290, 280, 270, 260, 250, 240, 230, 220, 210, 200, 190, 180, 170, 160, 150, 140, 130, 120, 110, 100])
ax.set_theta_zero_location('W', offset=-180)


ax.set_legend(loc=(-0.08, -0.08))
ax.set_title("Wind Rose")

plt.show()


![Capture22](https://user-images.githubusercontent.com/79433151/113241081-efe8a000-92e8-11eb-9d3b-08dc683a7a5a.PNG)

**Comment by cheikhnatm** [comment] 2021-04-02 15:12
Hello @FFT1368, I was wondering which parameters control the values of the frequency ? to have them spaced evenly ? in this picture for example.

![Capture](https://user-images.githubusercontent.com/77613198/113427982-497ac880-93d6-11eb-862b-f08e96cb5400.PNG)

Thank you in advance

**Comment by swartmilan** [comment] 2021-04-04 16:23
@FFT1368 Thank you for responding! 
I'd like to check my understanding of the _set_theta_zero_location_ function with you if you wouldn't mind. 
So the default in matplotlib projections is theta=0° at the EAST location, but most windmasts measure a 0° wind direction at NORTH (I'm presuming your companies data has theta=0° at the WEST location?); so to have matplotlib plot the 0° data at the NORTH location in my case, one has to use the _offset=_ kwarg; does the _loc=_ kwarg then just give the label for the new theta=0° location then?
Essentially, the _offset_ kwarg is the main one that determines the rotation of the data relative to EAST?

@cheikhnatm I think you can go into the _windrose.py_ package where it is installed locally and change the radii label spacing where it calculates it _radii=np.linspace(0, rmax, N + 1)_ 
Something like
```
def set_radii_angle(self, **kwargs):
  N = 6
  rmax = 12
  radii = np.linspace(0, rmax, N + 1)
```
let me know if this works please :)

**Comment by ocefpaf** [comment] 2022-05-06 14:24
This was fixed in https://github.com/python-windrose/windrose/issues/165

Please open a new issue if this resurfaces.

**Closed by ocefpaf** 2022-05-06 14:24 UTC

**Comment by PurveshPatel96** [comment] 2022-07-30 07:33
> Hello @FFT1368, I was wondering which parameters control the values of the frequency ? to have them spaced evenly ? in this picture for example.
> 
> ![Capture](https://user-images.githubusercontent.com/77613198/113427982-497ac880-93d6-11eb-862b-f08e96cb5400.PNG)
> 
> Thank you in advance

**Comment by PurveshPatel96** [comment] 2022-07-30 07:34
How do you mentioned the % value as a normed/frequency ?

thank you in advance

**Comment by robertburry** [comment] 2023-03-24 14:07
> And for having all the grids and numbers every 10 degrees you can use this improved version:
> 
> from windrose import WindroseAxes from matplotlib import pyplot as plt import matplotlib.cm as cm import numpy as np plt.figure()
> 
> ws = np.random.random(500) * 25 wd = np.random.random(500) * 360 ax = WindroseAxes.from_ax() plt.style.use('fast') ax.bar(wd, ws, nsector= 36,opening=0.94, bins=np.arange(0, 31, 5),edgecolor='gray',lw=0.1) ax.set_thetagrids(range(0,360,10),[90, 80, 70, 60, 50, 40, 30, 20, 10, 0, 350, 340, 330, 320, 310, 300, 290, 280, 270, 260, 250, 240, 230, 220, 210, 200, 190, 180, 170, 160, 150, 140, 130, 120, 110, 100]) ax.set_theta_zero_location('W', offset=-90) ax.set_theta_direction(-1)
> 
> ax.set_legend() ax.set_title("Wind Rose")
> 
> plt.show()

I had a similar issue as the original poster. This solution did help (I needed to remove the `ax.set_theta_direction(-1)` for my dataset). But I figured I would add what I ended up doing to make this abit easier for some. 

Instead of constructing the list myself I wrote it into a List Comprehension: 
`[(i + 360) if i < 0 else i for i in range(90,-270,-10)])`

so combined it looks like: 
`ax.set_thetagrids(range(0,360,10),[(_+360) if _ < 0 else _ for _ in range(90,-270,-10)])`

Which gave me the result I was looking for. 
![output](https://user-images.githubusercontent.com/20681032/227543525-18f4cfc3-e40e-4519-9652-0ff9e554afdc.png)

**Comment by ocefpaf** [comment] 2023-03-24 14:11
@robertburry this is a closed issue but your comment/code is nice and valid. Do you mind opening a new one with the updated info?
