### ISSUE TITLE
MatplotlibDeprecationWarning

### ISSUE THREAD

**Issue by bnando** [python-windrose/windrose#129] opened 2020-02-28 20:12 UTC
When using windrose library, the following deprecation warning is always displayed:

```
C:\Python 3.7.2\lib\site-packages\windrose\windrose.py:30: MatplotlibDeprecationWarning:
The dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use inspect.getdoc() instead.
  return lambda func: addendum(docstring.copy_dedent(base)(func))
```

warnings.filterwarnings("ignore") doesn't clear this message

**Comment by scls19fr** [comment] 2020-02-28 20:44
Hello,

It seems to me that it's a duplicate of #117
Fixed by #118
Please use latest development version
https://github.com/python-windrose/windrose#install-latest-development-version

Kind regards

**Closed by scls19fr** 2020-02-28 20:44 UTC
